#!/bin/bash
# Recovery publish for 2026-08-03. Generated by brief-morning after a sandbox-proxy publish failure.
# The brief content is validator-clean and fact-gate-clean. Nothing needs editing.
set -e
cd "$(dirname "$0")"
python3 .claude/skills/publish-brief/scripts/publish.py content/daily-updates/2026-08-03.md --date 2026-08-03
echo "--- post-publish distribution ---"
SNAPSHOT_SECRET=$(grep '^SNAPSHOT_SECRET=' .env.local | cut -d= -f2)
curl -sf -X POST "https://cosmictrex.com/api/publish/complete" -H "Authorization: Bearer $SNAPSHOT_SECRET"
echo
node --experimental-strip-types scripts/append-geo-lead.ts 2026-08-03
