/**
 * /api/distribute — Automated distribution endpoint
 *
 * Fires after brief publishes: sends email to subscribers via Resend,
 * posts to X/Twitter via OAuth 2.0.
 *
 * X post content uses dual-source strategy:
 *   1. Redis (primary) — AI-generated by daily-x-post scheduled task,
 *      stored via /api/x-post/store (key: x-post:YYYY-MM-DD)
 *   2. Thread generator (fallback) — code-based extraction from the
 *      published brief light via lib/social/thread-generator.ts
 *
 * This ensures posts always go out even if the scheduled task hasn't run.
 *
 * Triggered by Vercel cron (daily) or manual POST.
 *
 * Query params:
 *   ?date=YYYY-MM-DD   — Distribute a specific date (defaults to latest)
 *   ?channel=email      — Email only
 *   ?channel=x          — X/Twitter only
 *   ?dry-run=true       — Preview, don't send
 *
 * Protected by CRON_SECRET / SNAPSHOT_SECRET.
 */

export const maxDuration = 120;

import { NextRequest, NextResponse } from 'next/server';
import { isCronAuthorized } from '@/lib/cron-auth';
import { getBriefLightByDate } from '@/lib/brief-light-parser';
import { resolvePublishDate } from '@/lib/publish-date';
import { runDistribute, type DistributeResults } from '@/lib/distribute/handler';
import { runDistributeIfNeeded } from '@/lib/distribute/run-if-needed';

export async function POST(req: NextRequest) {
  if (!isCronAuthorized(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { date: dateSlug, manual } = resolvePublishDate(req.nextUrl.searchParams.get('date'));
  const channel = req.nextUrl.searchParams.get('channel') as 'email' | 'x' | null;
  const dryRun = req.nextUrl.searchParams.get('dry-run') === 'true';

  if (!manual && !getBriefLightByDate(dateSlug)) {
    console.warn(`[distribute] No brief for ${dateSlug} — skipping distribution (no stale fallback).`);
    return NextResponse.json({ date: dateSlug, skipped: true, reason: `No brief published for ${dateSlug}` });
  }

  console.log(`[distribute] Starting — date=${dateSlug}, channel=${channel || 'all'}, dryRun=${dryRun}`);

  let results: DistributeResults;

  if (dryRun) {
    results = await runDistribute({ dateSlug, dryRun, channel });
  } else {
    results = await runDistributeIfNeeded({ dateSlug, channel });
    if (results.email?.details?.includes('skipped')) {
      console.log('[distribute] Email: ⏭️ skipped — already sent');
    }
    if (results.x?.details?.includes('skipped')) {
      console.log('[distribute] X: ⏭️ skipped — already posted');
    }
  }

  const allSuccess = Object.values(results).every((r) => r.success);

  return NextResponse.json(
    {
      date: dateSlug,
      dryRun,
      results,
      success: allSuccess,
    },
    { status: allSuccess ? 200 : 207 },
  );
}

export async function GET(req: NextRequest) {
  return POST(req);
}
