/**
 * /api/distribute — Automated distribution endpoint
 *
 * Fires after brief publishes: sends email to subscribers via Resend,
 * posts long-form X post via OAuth 2.0.
 *
 * X post content is pre-generated by the daily-x-post scheduled task
 * and stored in Upstash Redis (key: x-post:YYYY-MM-DD) via /api/x-post/store.
 * This route reads from Redis and posts to X.
 *
 * Triggered by Vercel cron (daily) or manual POST.
 *
 * Query params:
 *   ?date=YYYY-MM-DD   — Distribute a specific date (defaults to latest)
 *   ?channel=email      — Email only
 *   ?channel=x          — X/Twitter only
 *   ?dry-run=true       — Preview, don't send
 *
 * Protected by CRON_SECRET / SNAPSHOT_SECRET.
 */

export const maxDuration = 120; // 2 minutes — enough for email batch + posting

import { NextRequest, NextResponse } from 'next/server';
import { Redis } from '@upstash/redis';
import { TwitterApi } from 'twitter-api-v2';
import { getBriefLightByDate, getLatestBriefLight } from '@/lib/brief-light-parser';
import { renderBriefEmail } from '@/lib/email/render-brief';
import { sendBatch } from '@/lib/email/resend-client';

// ─── Auth (matches other cron endpoints) ───────────────────────────────────

function isAuthorized(req: NextRequest): boolean {
  const snapshotSecret = process.env.SNAPSHOT_SECRET;
  const cronSecret = process.env.CRON_SECRET;

  if (!snapshotSecret && !cronSecret) {
    console.error('[distribute] Neither SNAPSHOT_SECRET nor CRON_SECRET is set');
    return false;
  }

  const secret = req.headers.get('x-snapshot-secret') || req.nextUrl.searchParams.get('secret');
  if (secret && snapshotSecret && secret === snapshotSecret) return true;

  const authHeader = req.headers.get('authorization');
  if (authHeader) {
    const token = authHeader.replace('Bearer ', '');
    if (cronSecret && token === cronSecret) return true;
    if (snapshotSecret && token === snapshotSecret) return true;
  }

  console.warn('[distribute] Auth failed.');
  return false;
}

// ─── Today's date in ET ────────────────────────────────────────────────────

function todaySlug(): string {
  const now = new Date();
  const et = new Date(now.toLocaleString('en-US', { timeZone: 'America/New_York' }));
  return et.toISOString().slice(0, 10);
}

// ─── Email distribution ────────────────────────────────────────────────────

async function distributeEmail(dateSlug: string, dryRun: boolean): Promise<{ success: boolean; details: string }> {
  if (!process.env.RESEND_API_KEY) {
    return { success: false, details: 'RESEND_API_KEY not set' };
  }

  const brief = getBriefLightByDate(dateSlug) || getLatestBriefLight();
  if (!brief) {
    return { success: false, details: `No brief light found for ${dateSlug}` };
  }

  const rendered = renderBriefEmail(brief);
  console.log(`[distribute] Email subject: ${rendered.subject}`);

  // Get subscribers from Redis
  const redis = new Redis({
    url: process.env.UPSTASH_REDIS_REST_URL!,
    token: process.env.UPSTASH_REDIS_REST_TOKEN!,
  });
  const recipients = (await redis.smembers('subscribers:emails')) as string[];
  console.log(`[distribute] Subscribers: ${recipients.length}`);

  if (recipients.length === 0) {
    return { success: true, details: 'No subscribers' };
  }

  if (dryRun) {
    return { success: true, details: `Would send to ${recipients.length} subscriber(s)` };
  }

  const result = await sendBatch(recipients, rendered.subject, rendered.html, {
    tags: [
      { name: 'type', value: 'daily-brief' },
      { name: 'date', value: brief.date },
    ],
  });

  return {
    success: result.failed.length === 0,
    details: `Sent ${result.sent}/${result.total}${result.failed.length > 0 ? `, ${result.failed.length} failed` : ''}`,
  };
}

// ─── Read pre-generated X post from Redis ─────────────────────────────────
//
// The daily-x-post scheduled task generates content via the X_Post_Generator
// skill and stores it in Redis (key: x-post:YYYY-MM-DD) via /api/x-post/store.

async function readXPost(dateSlug: string): Promise<{ mainPost: string; reply: string } | null> {
  const redis = new Redis({
    url: process.env.UPSTASH_REDIS_REST_URL!,
    token: process.env.UPSTASH_REDIS_REST_TOKEN!,
  });

  const key = `x-post:${dateSlug}`;
  const raw = await redis.get(key);

  if (!raw) {
    console.warn(`[distribute] No x-post found in Redis for key ${key}`);
    return null;
  }

  const data = typeof raw === 'string' ? JSON.parse(raw) : raw;

  if (!data.mainPost) {
    console.warn('[distribute] x-post in Redis missing mainPost field');
    return null;
  }

  return { mainPost: data.mainPost, reply: data.reply };
}

// ─── X/Twitter distribution ───────────────────────────────────────────────

async function distributeX(dateSlug: string, dryRun: boolean): Promise<{ success: boolean; details: string }> {
  const hasOAuth2 = Boolean(process.env.TWITTER_OAUTH2_ACCESS_TOKEN && process.env.TWITTER_CLIENT_ID);
  if (!hasOAuth2) {
    return { success: false, details: 'Twitter OAuth 2.0 credentials not set' };
  }

  // Read pre-generated X post from Redis (written by daily-x-post scheduled task via /api/x-post/store)
  const generated = await readXPost(dateSlug);
  if (!generated) {
    return { success: false, details: `No x-post found in Redis for ${dateSlug}. The daily-x-post task may not have run yet.` };
  }

  console.log(`[distribute] X post loaded: ${generated.mainPost.length} chars main, ${generated.reply.length} chars reply`);

  if (dryRun) {
    return {
      success: true,
      details: `Would post (${generated.mainPost.length} chars):\n\n${generated.mainPost}\n\n--- REPLY ---\n\n${generated.reply}`,
    };
  }

  // Refresh the OAuth 2.0 token before posting (tokens expire every 2 hours)
  const clientId = process.env.TWITTER_CLIENT_ID!;
  const clientSecret = process.env.TWITTER_CLIENT_SECRET || '';
  const refreshToken = process.env.TWITTER_OAUTH2_REFRESH_TOKEN;

  let accessToken = process.env.TWITTER_OAUTH2_ACCESS_TOKEN!;

  if (refreshToken) {
    try {
      console.log('[distribute] Refreshing X OAuth 2.0 token...');
      const authClient = new TwitterApi({ clientId, clientSecret });
      const refreshResult = await authClient.refreshOAuth2Token(refreshToken);
      accessToken = refreshResult.accessToken;
      console.log('[distribute] Token refreshed successfully');
    } catch (refreshErr) {
      console.warn('[distribute] Token refresh failed, trying existing token:', refreshErr instanceof Error ? refreshErr.message : String(refreshErr));
    }
  }

  const client = new TwitterApi(accessToken);

  try {
    // Post the main post (long-form, no char limit for Premium)
    const mainResult = await client.v2.tweet(generated.mainPost);
    const mainTweetId = mainResult.data.id;
    console.log(`[distribute] Main post published: ${mainTweetId}`);

    // Wait before replying
    await new Promise<void>((resolve) => setTimeout(resolve, 3000));

    // Post the self-reply with sign-off + link
    const replyResult = await client.v2.reply(generated.reply, mainTweetId);
    const replyTweetId = replyResult.data.id;
    console.log(`[distribute] Reply published: ${replyTweetId}`);

    return {
      success: true,
      details: `Post published: https://x.com/i/status/${mainTweetId}`,
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      details: `X posting failed: ${msg}`,
    };
  }
}

// ─── Route handler ─────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  if (!isAuthorized(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const dateSlug = req.nextUrl.searchParams.get('date') || todaySlug();
  const channel = req.nextUrl.searchParams.get('channel'); // 'email' | 'x' | null (both)
  const dryRun = req.nextUrl.searchParams.get('dry-run') === 'true';

  console.log(`[distribute] Starting — date=${dateSlug}, channel=${channel || 'all'}, dryRun=${dryRun}`);

  const results: Record<string, { success: boolean; details: string }> = {};

  // Email
  if (!channel || channel === 'email') {
    try {
      results.email = await distributeEmail(dateSlug, dryRun);
    } catch (err) {
      results.email = { success: false, details: `Error: ${err instanceof Error ? err.message : String(err)}` };
    }
    console.log(`[distribute] Email: ${results.email.success ? '✅' : '❌'} ${results.email.details}`);
  }

  // X/Twitter
  if (!channel || channel === 'x') {
    try {
      results.x = await distributeX(dateSlug, dryRun);
    } catch (err) {
      results.x = { success: false, details: `Error: ${err instanceof Error ? err.message : String(err)}` };
    }
    console.log(`[distribute] X: ${results.x.success ? '✅' : '❌'} ${results.x.details}`);
  }

  const allSuccess = Object.values(results).every(r => r.success);

  return NextResponse.json({
    date: dateSlug,
    dryRun,
    results,
    success: allSuccess,
  }, { status: allSuccess ? 200 : 207 }); // 207 Multi-Status if partial failure
}

// Vercel cron sends GET requests
export async function GET(req: NextRequest) {
  return POST(req);
}
