/**
 * Resolve X post content for distribution.
 *
 * Priority:
 *   1. Redis (x-post:YYYY-MM-DD) — AI-generated by daily-x-post task
 *   2. thread-generator — code-based fallback from published brief
 */

import { Redis } from '@upstash/redis';
import { parseRedisJson } from '@/lib/social/x-oauth';
import { generateThreadFromDate, generateThreadForLatest } from '@/lib/social/thread-generator';

export interface XPostContent {
  posts: string[];
  source: 'redis (AI-generated)' | 'thread-generator (code-based fallback)';
}

async function readXPostFromRedis(dateSlug: string): Promise<{ mainPost: string; reply?: string } | null> {
  const url = process.env.UPSTASH_REDIS_REST_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN;
  if (!url || !token) return null;

  const redis = new Redis({ url, token });
  const key = `x-post:${dateSlug}`;
  const raw = await redis.get(key);
  const data = parseRedisJson<{ mainPost?: string; reply?: string }>(raw);

  if (!data?.mainPost) return null;
  return {
    mainPost: data.mainPost,
    ...(data.reply ? { reply: data.reply } : {}),
  };
}

function buildPostsFromRedis(post: { mainPost: string; reply?: string }): string[] {
  const posts = [post.mainPost];
  if (post.reply?.trim()) {
    posts.push(post.reply.trim());
  }
  return posts;
}

export async function resolveXPostContent(dateSlug: string): Promise<XPostContent | null> {
  const redisPost = await readXPostFromRedis(dateSlug);

  if (redisPost) {
    return {
      posts: buildPostsFromRedis(redisPost),
      source: 'redis (AI-generated)',
    };
  }

  const threadFallback = generateThreadFromDate(dateSlug) || generateThreadForLatest();
  if (!threadFallback) return null;

  return {
    posts: threadFallback.tweets.map((tweet) => tweet.text),
    source: 'thread-generator (code-based fallback)',
  };
}
